name: Cluster Configuration
on: 
  workflow_dispatch:
    inputs:
      Operation: 
        description: "create or delete"
        default: 'create'
        required: true
env:
  WORKSPACE: ${{ github.event.inputs.instance }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: 5efa86ae-29bc-4760-a1db-51bde40f2fad
    
jobs:
  Create:
    name: Create cluster
    if: ${{ github.event.inputs.Operation == 'create' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: 0.14.2
      
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Configure working directory
        id: wd
        run: |
          echo "::set-output name=directory::./$WORKSPACE"

      - name: Terraform init
        id: init
        working-directory: ./${{ steps.wd.outputs.directory }}
        run: |
          terraform init -input=false

      - name: Terraform plan 
        id: plan
        working-directory: ./${{ steps.wd.outputs.directory }}
        run: |
          terraform plan -out plan.out -input=false
          
      - name: Terraform apply 
        id: apply
        working-directory: ./${{ steps.wd.outputs.directory }}
        run: |
          terraform apply -input=false -auto-approve plan.out
  
  Destroy:
    name: Destroy Cluster
    if: ${{ github.event.inputs.Operation == 'delete' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: 0.14.2
      
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Configure working directory
         id: wd
         run: |
          echo "::set-output name=directory::./$WORKSPACE"
          ls

      - name: Terraform init
        id: init
        working-directory: ./${{ steps.wd.outputs.directory }}
        run: |
          terraform init -input=false

      - name: Terraform destroy 
        id: destroy
        working-directory: ./${{ steps.wd.outputs.directory }} 
        run: |
          terraform destroy -input=false -auto-approve
